name: "upload build to release"
description: "uploads a compiled build to the new github release"
inputs:
  release_tag:
    description: "The release tag"
    required: true
  build_path:
    description: "The path to the build"
    required: true
  build_name:
    description: "The name of the build"
    required: true
  build_content_type:
    description: "The content type of the build"
    required: true
  build_name_prefix:
    description: 'The prefix to be added to the display name of the uploaded build. ie mac-, alpine-'
    required: true
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: Brightspace/third-party-actions@actions/checkout
    - name: upload
      env:
        RELEASE_TAG: ${{ inputs.release_tag }}
        BUILD_NAME: ${{ inputs.build_name }}
        BUILD_PATH: ${{ inputs.build_path }}
        BUILD_NAME_PREFIX: ${{ inputs.build_name_prefix }}
        CONTENT_TYPE: ${{ inputs.build_content_type }}
        GITHUB_TOKEN: ${{ github.token }}
      working-directory: src/D2L.Bmx
      run: |
        echo "Uploading build to release $RELEASE_TAG"
        cd $BUILD_PATH
        $NEW_FILE_NAME="$BUILD_PREFIX-$BUILD_NAME"
        mv "$BUILD_NAME" "$NEW_FILE_NAME"

        gh release upload "$RELEASE_TAG" "$NEW_FILE_NAME" \
          --name "$BUILD_NAME_PRESET$BUILD_NAME" \
          --content-type $CONTENT_TYPE
      shell: bash
