name: "create release"
description: "Creates a new GitHub release with incremented version"
inputs:
  version:
    description: 'Version number for the new release'
    required: false
    default: '3.0.0'
outputs:
  release_tag:
    description: "The tag of the created release"
    value: ${{ steps.create_release.outputs.release_tag }}
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: Brightspace/third-party-actions@actions/checkout
    - run: sudo apt-get update && sudo apt-get install -y jq bc
      shell: bash
    - name: create release
      id: release_tag
      run: |
        $version = "${{ inputs.version }}"

        $RELEASE_TAG = "v$version"
        echo "release_tag=$RELEASE_TAG" >> GITHUB_OUTPUT

        gh release create "$RELEASE_TAG" `
          --title "Release $RELEASE_TAG" `
          --notes "Release notes for version $RELEASE_TAG"
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ github.token }}
