name: "Apply labels to PRs"
on:
  - pull_request
jobs:
  label:
    runs-on: [self-hosted, Linux, AWS]
    timeout-minutes: 2
    steps:
      - uses: Brightspace/third-party-actions@actions/labeler
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Brightspace/third-party-actions@codelytv/pr-size-labeler
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "10"
          s_max_size: "50"
          m_max_size: "200"
          l_max_size: "500"
          fail_if_xl: "false"
          message_if_xl: ""
