name: Build & Test
on:
  push:
    paths:
      - "*.go"
      - "*/*.go"
      - "*/*/*.go"
      - "*/*/*/*.go"
      - "*/*/*/*/*.go"
      - "*/*/*/*/*/*.go"
      - .github/workflows/main.yml

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Vet
        run: go vet ./...
      - name: Code Coverage Tools
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
      - name: Test
        run: go test -v -covermode="count" -coverprofile="coverage.out" ./...
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
