name: publish docker

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/publish_docker.yml"
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/publish_docker.yml"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: Debian11
            tag: "7.0"
          - os: Alpine3.17
            tag: 7.0-alpine
          - os: Alpine3.16
            tag: 7.0-alpine3.16
          - os: Ubuntu22.04
            tag: 7.0-jammy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: publish
        shell: pwsh
        env:
          OS: ${{ matrix.os }}
          TAG: ${{ matrix.tag }}
        run: |
          $DOCKER_BUILTKIT = 1
          docker build --build-arg "TAG=$env:TAG" --build-arg "OS=$env:OS" .
