name: publish

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/publish.yml"
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/publish.yml"
  repository_dispatch:
    types: [create-release]
  workflow_dispatch:


jobs:
  create_release:
    #if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.create_release.outputs.release_tag }}
    steps:
      - name: Create release
        id: create_release
        uses: ./.github/actions/create-release

  build:
    if: ${{ always() }}
    needs: create_release
    strategy:
      matrix:
        include:
          - machine: windows-latest
            platform: win
            content_type: application/vnd.microsoft.portable-executable
            file_name: D2L.Bmx.exe
          - machine: macos-latest
            platform: osx
            content_type: application/octet-stream
            file_name: D2L.Bmx
    runs-on: ${{ matrix.machine }}
    timeout-minutes: 10
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: publish
        shell: pwsh
        working-directory: src/D2L.Bmx
        run: |
          dotnet publish -r $env:PLATFORM-x64 -c Release -o build
          cd build
          ls
      - name: upload build
        #if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github.actions/upload-build-to-release
        with:
          release_tag: ${{ needs.create_release.outputs.release_tag }}
          build_path: build
          build_name: ${{ matrix.file_name }}
          build_content_type: ${{ matrix.content_type }}
          build_name_prefix: ${{ inputs.platform }}

  build_docker:
    if: ${{ always() }}
    needs: create_release
    strategy:
      matrix:
        include:
          - file: Dockerfile.ubuntu
            platform: ubuntu
          - file: Dockerfile.alpine
            platform: alpine
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: publish
        shell: pwsh
        env:
          DOCKERFILE: ${{ matrix.file }}
        run: |
          docker buildx build -f $env:DOCKERFILE -o build .
          cd build
          ls
      - name: upload build
        #if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./.github.actions/upload-build-to-release
        with:
          release_tag: ${{ needs.create_release.outputs.release_tag }}
          build_path: build
          build_name: D2L.Bmx
          build_content_type: application/x-executable
          build_name_prefix: ${{ matrix.platform }}
