name: GitHub Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Validate config
        uses: docker://goreleaser/goreleaser@sha256:83ea87528d24d5c5cafa92674f79ccdd5fad6d6fbb906d0925e8913e3e3f4248
        with:
          args: check
      - name: Release
        uses: docker://goreleaser/goreleaser@sha256:83ea87528d24d5c5cafa92674f79ccdd5fad6d6fbb906d0925e8913e3e3f4248
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
